### ISSUE TITLE
Example on how to query CDP via user address

### ISSUE THREAD

**Issue by herman-rogers** [Destiner/maker-subgraph#1]
Is this possible with this subgraph to query a users current CDP from their address?

**Comment by Destiner** [comment]
I've just updated subgraph so it should be possible when newest version will sync.

Query (note that CDPs usually owned by proxy not the user)
```gql
{
  user(id: "0x7d6149ad9a573a6e2ca6ebf7d4897c1b766841b4") {
    proxy {
      cdps {
        vault {
          collateral {
            id
          }
          debt
          supply
        }
      }
    }
  }
}

```

**Comment by herman-rogers** [comment]
ok thanks for that - had the chance to test it and even with the proxy contract address it returns `user:null`. If I plug the same address into dai.js it returns the user's vault as expected. Maybe vaults aren't supported yet?

**Comment by herman-rogers** [comment]
Able to work around it for the moment by getting the proxy address, gathering the id's for the values and running the below query.

```
{
  cdp(id: <id>) {
    vault {
      debt
      supply
    }
  }
}
```

Good enough for now
